


[server]
port = 80
enableXsrfProtection=false

[logger]
level = "debug"

[browser]
gatherUsageStats = false

[theme]
base="light"
primaryColor="#4cc5d6"

[global]
dataFrameSerialization = "legacy"
